### ISSUE TITLE
Add links for each implementation details modal

### ISSUE THREAD

**Issue by harrel56** [bowtie-json-schema/bowtie#333] opened 2023-07-10 15:48 UTC
So, implementation details can also include "additional" links, which is basically a map of url -> description. Looks like all the data is accessible in code, but it just needs to be displayed. Maybe even more data could be displayed like: homepage, issues url - there probably would be some redundancy, but why not?
![image](https://github.com/bowtie-json-schema/bowtie/assets/26698228/5ea7f583-f587-4d34-8fa2-c4ab1caf3196)

**Comment by Siddharth-Singh-2004** [comment] 2024-02-11 04:23
@Julian , I am looking this. Kindly assign this to me.

**Comment by Siddharth-Singh-2004** [comment] 2024-02-14 10:06
@harrel56, I included implementation elements as requested. Is there anything else you are looking for in terms of "additional data" in the Implementation Details screen? Once all elements are covered, I will reorganise the UI to utilise the header space better by bringing in appropriate grid layouts. Since data is not uniform in length and wrapping is not a good idea with links, I will propose the final look incorporating all the elements, which you may approve.

<img width="1224" alt="Implementation Details Modal" src="https://github.com/bowtie-json-schema/bowtie/assets/112953828/6557bd8c-b5f2-4b58-b455-754ac09c70f5">

cc @Julian, any feedback from your side is most welcome.

**Comment by harrel56** [comment] 2024-02-14 10:41
And it looks like it's no longer a dialog, but a separate page, like: https://bowtie.report/#/implementations/java-json-schema

So the changes should be applied here

**Comment by Siddharth-Singh-2004** [comment] 2024-02-14 11:02
@harrel56, 
Just to clarify: You want to see the data in here... in the UI
export interface Implementation {
... 
...
 links?: {
    description?: string;
    url?: string;
    [k: string]: unknown;
  }[];
...

As I see it, the place where this information is really useful, is on the Details screen so the implementer can check for context around test case failures.  Since, you  are the implementer of the Java schema, you may please let me know the best place to make the additions so you have all the data you need in one place.

**Comment by harrel56** [comment] 2024-02-14 11:36
Yeah, that's exactly the part of data I'd want to display. Although, I'm not really aware what data can we expect in additional fields here ([k: string]: unknown) - so I'd just ignore it for now.

As for the specific place where to display this data - I'd definitely go for a page which I sent before. "details" dialog does not contain any other implementation info other than failed test cases. But ofc it's just my point of view

**Comment by Siddharth-Singh-2004** [comment] 2024-02-14 12:21
@harrel56 ,
What you meant by " I'd definitely go for a page which I sent before...",  is...: 
the form that comes up on clicking  the hyperlink of the schema implementation... as shown here...
but, this one is no longer a dialog.

Kindly clarify.

<img width="450" alt="Screenshot 2024-02-14 at 5 47 59 PM" src="https://github.com/bowtie-json-schema/bowtie/assets/112953828/ac35d13a-acfd-49f4-aa3d-d28e7e728426">

**Comment by harrel56** [comment] 2024-02-14 13:17
Yes, exactly, some time before there was no dedicated page for implementation info but just a simple dialog. Now we have a full page for that. So we should add links data to this page. There is no requirement for a dialog of any kind. Just please put the additional info somewhere near the other infos (homepage, issues, versions etc.)

**Comment by Siddharth-Singh-2004** [comment] 2024-02-14 13:21
Thanks for the clarification. I will have the links included.

**Comment by Siddharth-Singh-2004** [comment] 2024-02-15 06:56
@harrel56,
Here is how the Implementation Info page looks like, after inclusion of "Additional Links", which takes the user to the linked URL. Kindly let me know if this meets your requirement.

<img width="1212" alt="Screenshot 2024-02-15 at 12 16 57 PM" src="https://github.com/bowtie-json-schema/bowtie/assets/112953828/5d2826da-649c-4a72-912b-61e60db023cd">

cc: @Julian

**Comment by harrel56** [comment] 2024-02-15 07:28
Nice! That's exactly what I had in mind. You can also ping me when you push PR with changes

**Comment by Siddharth-Singh-2004** [comment] 2024-02-15 11:35
@harrel56, the pull request #879 is ready for review.

**Closed** 2024-02-15 13:17 UTC
Labels: good first issue, frontend-ux

**Comment by Siddharth-Singh-2004** [comment] 2024-02-15 13:21
@harrel56,

Sorry for the back and forth. The shortened code seems to be causing issue with the UI.

Picking a schema that has not provided additional links, for example, jsonschema Go (1st one on the list).

The shortened code, implementation.links?.length, leads to a UI bug (see the 0 displayed):

<img width="954" alt="Screenshot 2024-02-15 at 6 45 32 PM" src="https://github.com/bowtie-json-schema/bowtie/assets/112953828/f4c888db-26ff-4bf3-ae92-e7cfe1279732">

The long form of code, implementation.links && !!implementation.links.length,  meets to expected behavior:
<img width="951" alt="Screenshot 2024-02-15 at 6 48 07 PM" src="https://github.com/bowtie-json-schema/bowtie/assets/112953828/d3cbcb87-f041-4e14-bf92-5766202bd4a9">

I'll revert to the original fix.
