### ISSUE TITLE
Opening and Closing `"Details"` modal for tests with many cases is slow and laggy in behaviour

### ISSUE THREAD

**Issue by adwait-godbole** [bowtie-json-schema/bowtie#1075] opened 2024-04-03 15:22 UTC
For cases with not much tests to show, the modal opens fast and smoothly but in case there are multiple cases to display in the modal, after click on the "Details" button it takes quite some time to open the modal and some time to close the modal as well giving the feel that nothing is happening on the button clicks.

https://github.com/bowtie-json-schema/bowtie/assets/68469605/ded56aa4-983b-4db4-a3f1-4e773106995b

A possible solution could be we just open the modal straight away and display a loading spinner instead. Not sure what could be a possible fix for the slow closing of the modal though :( and in fact why is it even happening.

@JeelRajodiya this is somewhat related to #1074 so you can have a look here as well if you wish to and thanks! :)

**Comment by sd1p** [comment] 2024-04-03 18:29
After going through the `Modal` code thoroughly, `TypeScript vscode-json-language-service` and  `JavaScript ajv` implementation each have 102 and 287 unsuccessful tests. 

Every time the modal opens, it goes through all 1235 tests and prepares a card component for each unsuccessful test. This is causing the inconsistent behavior of the modals.

**Comment by Julian** [comment] 2024-04-04 13:01
I don't recall this being the case prior to us syntax highlighting schemas I think? Someone should likely double check whether that's the cause.

Surely creating 1235 cards shouldn't be a big deal.

**Comment by sd1p** [comment] 2024-04-04 14:21
Without syntax highlighting every modal is opening instantly. 

https://github.com/bowtie-json-schema/bowtie/assets/43758514/4e8ca76a-8a89-469b-88ef-88ee159ebf9f

**Comment by Julian** [comment] 2024-04-04 14:24
That's pretty poor, as syntax highlighting that many cases shouldn't be that slow either, but probably a fix then is to only syntax highlight things when they're in view in the viewport or something.

**Comment by JeelRajodiya** [comment] 2024-04-04 14:54
@sd1p I observed reduction in the lags when I reverted the modifications introduced in the commit [873d44e6448c3f0d1889848ab8f699ea41f5138a](https://github.com/bowtie-json-schema/bowtie/commit/873d44e6448c3f0d1889848ab8f699ea41f5138a)

**Comment by sd1p** [comment] 2024-04-04 14:56
I want to try fixing this issue.

1. We will render all the cards without syntax highlighting.
2. If the card is in/near viewport we will highlight the syntax.

**Comment by Julian** [comment] 2024-04-21 08:23
Fixed in #1077 I believe.

**Closed by Julian** 2024-04-21 08:23 UTC
Labels: bug, frontend-ux
